import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const interFont = Inter({
  variable: "--inter",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${interFont.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${interFont.className}`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
